AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Security/Eval:
  Enabled: false

# not a Rails project
RSpec/Rails:
  Enabled: false

require:
  - rubocop-rake
  - rubocop-rspec
